apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-pvc-testing
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: release-sc-high
---
apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  annotations:
    diamanti.com/endpoint: none
spec:
  containers:
  - image: centos:7.5.1804
    command: ["tar"]
    args:
      - "-xvpz"
      - "--file=/backup-dir/tar-backup-qa-portal-release-pvc-1623049261.tar.gz"
      - "--strip-components=1"
      - "-C"
      - "/data"
      - "--numeric-owner"
    name: tar-backup
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /data
      name: release-pvc-testing
    - mountPath: /backup-dir
      name: backup-vol
  restartPolicy: OnFailure
  volumes:
  - name: release-pvc-testing
    persistentVolumeClaim:
      claimName: release-pvc-testing
  - name: backup-vol
    persistentVolumeClaim:
      claimName: nfs-pvc
