apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backupcronjob
  namespace: qa-portal
spec:
  schedule: "*/1 * * * *"
  #schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: qa-backup
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: diamanti.com/app
                    operator: In
                    values: ["backupcontroller"]  # Ensures only 1 backcontroller runs in the cluster
                topologyKey: beta.kubernetes.io/os
          containers:
          - args:
            - -virtualIP=172.16.19.76                   # Virtual IP address of the cluster
            - -sourcePVC=release-pvc               # PVC to take a backup of associated volume
            - -pvcNamespace=qa-portal                # Namespace
            - -backupPlugin=tar                    # Backup plugin type
            - -pluginArgs={"server":"172.16.0.25","path":"\/dws_nas_scratch\/release-portal-backup","mountOptions":"nfsvers=3"}   # Backup plugin args
            - -pluginOptions=["-cvp","--selinux","--acls","--xattrs"] # Backup plugin options
            - -compressed=true                     # Flag to enable/disable compression
            - -maxNumSnapshots=10                   # Maximum number of snapshots that can exist for the PVC
            - -numDaysToKeep=180                    # Maximum number of backups that can exist on NFS server
            - -activeVolumesOnly=true              # Flag to backup attached volumes only
            - -cpuResource=100m                    # CPU resource for backup agent
            - -memoryResource=100Mi                # Memory resource for backup agent
            - -maxConcurrentJobs=1                # Max concurrent backup agents
            - -snapshotPromoter={"ext3":"backup-ext3-sc","ext4":"backup-ext4-sc","xfs":"backup-xfs-sc"} #Storage class for creating volume from a snapshot
            name: backupjob-release-pvc
            image: diamanti/backupcontroller:v3.1.0
            volumeMounts:
            - name: cluster-config
              mountPath: /etc/diamanti
              readOnly: true
          volumes:
          - name: cluster-config
            hostPath:
              path: /etc/diamanti
              type: Directory
          restartPolicy: OnFailure
