# Generated by Django 2.2.7 on 2020-01-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0001_DDB'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_info',
            name='OrchestrationPlatform',
        ),
    ]
