"""
Django settings for dp project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from constraints import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ltib)xdl5(i3+u^fjf*5fy**us+7r@21t)y6kmx($g4mdk6b&w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DDB',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'universal',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'CentOS-DCX-2.4.1': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'CentOS-DCX-2.4.1',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DCX-2.4.1': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DCX-2.4.1',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DCX-3.2.0': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DCX-3.2.0',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DCX-3.1.0': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DCX-3.1.0',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'OCP-4.5': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'OCP-4.5',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DSS-3.1': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DSS-3.1',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'Overlay-3.1': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Overlay-3.1',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DCX-3.0': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DCX-3.0',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DMC Master': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DMC Master',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DMC-3.0': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DMC-3.0',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },

    'DMC-3.1': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DMC-3.1',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },

    'universal': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'universal',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'master': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'master',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'Spektra 2.4': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '2.4.0',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'DCX-DMC-Master': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DCX-DMC-Master',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    '2.3.0': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '2.3.0',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
    'TestDatabase': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'TestDatabase',
        'USER': userName,
        'PASSWORD': passwd,
        'HOST': hostName,
        'PORT': portNumber,
        },
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# STATIC_ROOT = '/home/sushil/pythonDB/temp/dp/static'

STATIC_URL = '/static/'

STATICFILES_DIRS=(
    os.path.join(BASE_DIR, "static"),
)
