# Generated by Django 3.0 on 2020-03-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0002_latest_tc_status1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LATEST_TC_STATUS1',
        ),
    ]
