# Generated by Django 3.0 on 2020-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0005_delete_latest_tc_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_info',
            name='Notes',
            field=models.TextField(blank=True, default='NO NOTES PROVIDED'),
        ),
    ]
