# Generated by Django 3.0 on 2020-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0006_auto_20200312_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_info',
            name='TcName',
            field=models.CharField(blank=True, default='TC NOT AUTOMATED', max_length=2000),
        ),
    ]
