# Generated by Django 3.0 on 2020-04-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0011_auto_20200416_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_info_gui',
            old_name='BrowserType',
            new_name='BrowserName',
        ),
    ]
