# Generated by Django 3.0 on 2020-06-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0013_gui_latest_tc_status_gui_tc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGSGUI',
            fields=[
                ('logNo', models.AutoField(primary_key=True, serialize=False)),
                ('tcInfoNum', models.IntegerField()),
                ('UserName', models.CharField(default='UNKNOWN', max_length=100)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('RequestType', models.CharField(max_length=10)),
                ('LogData', models.TextField()),
                ('URL', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
