# Generated by Django 3.0 on 2020-07-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0017_auto_20200723_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(default='UNKNOWN', max_length=100)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Build', models.CharField(blank=True, max_length=100, null=True)),
                ('Tag', models.CharField(blank=True, max_length=100, null=True)),
                ('Result', models.CharField(blank=True, max_length=14, null=True)),
                ('Bugs', models.CharField(blank=True, max_length=500, null=True)),
                ('CardType', models.CharField(blank=True, max_length=100, null=True)),
                ('NoOfTCsPassed', models.IntegerField(blank=True, null=True)),
                ('UIFocus', models.TextField(blank=True, null=True)),
                ('UISkipList', models.TextField(blank=True, null=True)),
                ('Setup', models.TextField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
