# Generated by Django 3.0 on 2020-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0018_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasebuildsinfo',
            name='failureCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='releasebuildsinfo',
            name='successCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releasebuildsinfo',
            name='buildNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releasebuildsinfo',
            name='jobName',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=100),
        ),
    ]
