# Generated by Django 3.0 on 2020-07-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0020_auto_20200729_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasebuildsinfo',
            name='buildName',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
