# Generated by Django 3.0 on 2020-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0022_remove_releasebuildsinfo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasebuildsinfo',
            name='ReleaseNumber',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
    ]
