# Generated by Django 3.0 on 2020-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0026_auto_20201123_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_info',
            name='epicLink',
        ),
        migrations.RemoveField(
            model_name='tc_info',
            name='fixVersion',
        ),
        migrations.AddField(
            model_name='releases',
            name='epicLink',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='releases',
            name='fixVersion',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='tc_info',
            name='OS',
            field=models.TextField(blank=True, default='NO OS'),
        ),
        migrations.AddField(
            model_name='tc_info_gui',
            name='OS',
            field=models.TextField(blank=True, default='NO OS'),
        ),
        migrations.AddField(
            model_name='tc_info_gui',
            name='stateUserMapping',
            field=models.TextField(blank=True, default='{"CREATED":"DEFAULT"}'),
        ),
    ]
