# Generated by Django 3.0 on 2020-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0027_auto_20201124_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info_gui',
            name='applicable',
            field=models.TextField(blank=True, default='Applicable'),
        ),
    ]
