# Generated by Django 3.0 on 2020-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0029_remove_tc_info_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info',
            name='OS',
            field=models.TextField(blank=True, default='NO OS'),
        ),
    ]
