# Generated by Django 3.0 on 2020-11-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0036_auto_20201124_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_info_gui',
            name='OS',
        ),
        migrations.RemoveField(
            model_name='tc_info_gui',
            name='applicable',
        ),
        migrations.RemoveField(
            model_name='tc_info_gui',
            name='stateUserMapping',
        ),
    ]
