# Generated by Django 3.0 on 2020-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0038_auto_20201124_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_info',
            name='OS',
            field=models.TextField(blank=True, default='NO OS', null=True),
        ),
    ]
