# Generated by Django 3.0 on 2021-01-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0040_auto_20210118_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info_gui',
            name='TcName',
            field=models.CharField(blank=True, default='TC NOT AUTOMATED', max_length=2000),
        ),
    ]
