# Generated by Django 3.1.6 on 2021-03-24 09:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0044_auto_20210309_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='releases',
            name='PlatformCli',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='releases',
            name='PlatformGui',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=10), blank=True, default=list, size=None),
        ),
    ]
