# Generated by Django 3.1.6 on 2021-03-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0045_auto_20210324_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releases',
            old_name='PlatformCli',
            new_name='PlatformsCli',
        ),
        migrations.RenameField(
            model_name='releases',
            old_name='PlatformGui',
            new_name='PlatformsGui',
        ),
    ]
