# Generated by Django 3.1.6 on 2021-03-30 05:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0046_auto_20210324_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='AssignedReleases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=20), blank=True, default=list, size=None),
        ),
    ]
