# Generated by Django 3.1.6 on 2021-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0047_user_info_assignedreleases'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='EngineerType',
            field=models.CharField(blank=True, choices=[('C', 'CLI'), ('G', 'GUI'), ('CG', 'CLI+GUI')], max_length=2, null=True),
        ),
    ]
