# Generated by Django 3.1.6 on 2021-03-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0048_user_info_engineertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='EngineerType',
            field=models.CharField(blank=True, choices=[('CLI', 'CLI'), ('GUI', 'GUI'), ('CLI+GUI', 'CLI+GUI')], max_length=7, null=True),
        ),
    ]
