# Generated by Django 3.2 on 2021-04-08 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0049_auto_20210331_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='PlatformsCli',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='releases',
            name='PlatformsGui',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='Platform',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tc_info_gui',
            name='Platform',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='AssignedReleases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=100), blank=True, default=list, size=None),
        ),
    ]
