# Generated by Django 3.2.12 on 2022-03-16 06:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0052_auto_20220301_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='releases',
            name='fixVList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
