# Generated by Django 3.0 on 2020-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LATEST_TC_STATUS1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TcID', models.CharField(max_length=200)),
                ('TcName', models.CharField(blank=True, max_length=2000)),
                ('Build', models.CharField(blank=True, max_length=1000)),
                ('Result', models.CharField(blank=True, max_length=14)),
                ('Bugs', models.CharField(blank=True, max_length=500)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Domain', models.CharField(blank=True, max_length=50)),
                ('SubDomain', models.CharField(blank=True, max_length=50)),
                ('CardType', models.CharField(default='NOT ENTERED', max_length=10)),
            ],
        ),
    ]
