# Generated by Django 3.0 on 2020-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0007_auto_20200327_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityWiseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priority', models.CharField(blank=True, max_length=5)),
                ('Pass', models.IntegerField(default=0)),
                ('Fail', models.IntegerField(default=0)),
                ('Skip', models.IntegerField(default=0)),
                ('NotTested', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='aggregate_tc_state',
            old_name='Fail',
            new_name='AutomatedFail',
        ),
        migrations.RenameField(
            model_name='aggregate_tc_state',
            old_name='Pass',
            new_name='AutomatedPass',
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='AutomatedSkip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='ManualFail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='ManualPass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='ManualSkip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='NonAutomated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='NotApplicable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='NotTested',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='Skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregate_tc_state',
            name='Tested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aggregate_tc_state',
            name='Domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='Priority',
            field=models.CharField(blank=True, default='P7', max_length=5),
        ),
    ]
