# Generated by Django 3.0 on 2020-04-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0007_auto_20200404_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DEFAULT_DOMAIN',
        ),
        migrations.DeleteModel(
            name='DEFAULT_SUBDOMAIN',
        ),
        migrations.DeleteModel(
            name='DEFAULT_VALUES',
        ),
    ]
