# Generated by Django 3.0 on 2020-04-16 06:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0009_default_domain_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_INFO_GUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TcID', models.CharField(max_length=200)),
                ('Domain', models.CharField(blank=True, default='UNKNOWN', max_length=50)),
                ('SubDomain', models.CharField(blank=True, default='UNKNOWN', max_length=50)),
                ('Scenario', models.CharField(blank=True, default='UNKNOWN', max_length=200)),
                ('Description', models.TextField(blank=True, default='NO DESCRIPTION PROVIDED')),
                ('Steps', models.TextField(blank=True, default='NO STEPS PROVIDED')),
                ('ExpectedBehaviour', models.CharField(blank=True, default='NO EXPECTED BEHAVIOUR PROVIDED', max_length=5000)),
                ('Notes', models.TextField(blank=True, default='NO NOTES PROVIDED')),
                ('CardType', models.CharField(blank=True, default=None, max_length=100)),
                ('ServerType', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=10), blank=True, size=None)),
                ('WorkingStatus', models.CharField(blank=True, default='CREATED', max_length=50)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Assignee', models.CharField(blank=True, default='UNKNOWN', max_length=50)),
                ('Creator', models.CharField(blank=True, default='ANONYMOUS', max_length=50)),
                ('Tag', models.CharField(blank=True, default='NO TAG', max_length=20)),
                ('Priority', models.CharField(blank=True, default='P4', max_length=5)),
                ('AutomatedTcName', models.CharField(blank=True, default='TC NOT AUTOMATED', max_length=2000)),
                ('BrowserType', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='e2e',
            old_name='Bug',
            new_name='Bugs',
        ),
    ]
