# Generated by Django 3.0 on 2020-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0010_auto_20200416_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='ReleaseNumber',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
