# Generated by Django 3.0 on 2020-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0012_auto_20200416_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='GUI_LATEST_TC_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcInfoNum', models.IntegerField(blank=True, null=True)),
                ('Build', models.CharField(blank=True, max_length=1000)),
                ('Result', models.CharField(blank=True, max_length=14)),
                ('Bugs', models.CharField(blank=True, max_length=500)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GUI_TC_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcInfoNum', models.IntegerField(blank=True, null=True)),
                ('Build', models.CharField(blank=True, max_length=1000)),
                ('Result', models.CharField(blank=True, max_length=14)),
                ('Bugs', models.CharField(blank=True, max_length=500)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
