# Generated by Django 3.0 on 2020-06-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0014_logsgui'),
    ]

    operations = [
        migrations.AddField(
            model_name='releases',
            name='DockerVersion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='HelmVersion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='KubernetesVersion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
