# Generated by Django 3.0 on 2020-07-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0021_releasebuildsinfo_buildname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasebuildsinfo',
            name='timeStamp',
        ),
    ]
