# Generated by Django 3.0 on 2020-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0023_releasebuildsinfo_releasenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info',
            name='stateUserMapping',
            field=models.TextField(blank=True, default='Not Mapped'),
        ),
    ]
