# Generated by Django 3.0 on 2020-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0024_tc_info_stateusermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info',
            name='applicable',
            field=models.TextField(blank=True, default='Applicable'),
        ),
        migrations.AlterField(
            model_name='tc_info',
            name='stateUserMapping',
            field=models.TextField(blank=True, default='{"CREATED":"DEFAULT"}'),
        ),
    ]
