# Generated by Django 3.0 on 2020-11-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0028_tc_info_gui_applicable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_info',
            name='OS',
        ),
    ]
