# Generated by Django 3.0 on 2020-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0030_tc_info_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info',
            name='epicLink',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='tc_info',
            name='fixVersion',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
    ]
