# Generated by Django 3.0 on 2020-11-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0031_auto_20201124_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_info',
            name='epicLink',
        ),
        migrations.RemoveField(
            model_name='tc_info',
            name='fixVersion',
        ),
    ]
