# Generated by Django 3.0 on 2020-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0033_auto_20201124_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='releases',
            name='epicLink',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='releases',
            name='fixVersion',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
    ]
