# Generated by Django 3.0 on 2020-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0035_auto_20201124_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_info_gui',
            name='OS',
            field=models.TextField(blank=True, default='NO OS', null=True),
        ),
        migrations.AlterField(
            model_name='tc_info_gui',
            name='applicable',
            field=models.TextField(blank=True, default='Applicable', null=True),
        ),
        migrations.AlterField(
            model_name='tc_info_gui',
            name='stateUserMapping',
            field=models.TextField(blank=True, default='{"CREATED":"DEFAULT"}', null=True),
        ),
    ]
