# Generated by Django 3.0 on 2021-02-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0041_tc_info_gui_tcname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platform', models.CharField(default='NO PLATFORM', max_length=100)),
                ('ApplicableTCs', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='releases',
            name='ParentRelease',
            field=models.CharField(default='master', max_length=50),
        ),
    ]
