# Generated by Django 3.1.6 on 2021-03-08 07:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0042_auto_20210205_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_info',
            name='Platform',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='UNKNOWN', max_length=10), blank=True, default=list, size=None),
        ),
    ]
