# Generated by Django 3.1.6 on 2021-03-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0043_tc_info_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUTOMATION_COUNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRange', models.DateTimeField()),
                ('TotalCli', models.IntegerField()),
                ('AutomatedCli', models.IntegerField()),
                ('TotalGui', models.IntegerField()),
                ('AutomatedGui', models.IntegerField()),
            ],
        ),
    ]
