# Generated by Django 3.1.6 on 2021-03-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0043_auto_20210309_0524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AUTOMATION_COUNT',
        ),
    ]
