# Generated by Django 3.1.6 on 2021-03-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0044_automation_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AUTOMATION_COUNT',
        ),
    ]
