# Generated by Django 3.1.6 on 2021-04-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0049_auto_20210405_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='PlatformsCli',
        ),
        migrations.RemoveField(
            model_name='releases',
            name='PlatformsGui',
        ),
    ]
