# Generated by Django 3.2.11 on 2022-02-15 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0050_auto_20210408_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='gui_latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AddField(
            model_name='gui_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AddField(
            model_name='latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AddField(
            model_name='releases',
            name='BuList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='releases',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='QAEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='RelNum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tc_info',
            name='Time',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='tc_info_gui',
            name='Time',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AlterField(
            model_name='latest_tc_status',
            name='CardType',
            field=models.CharField(default='NOT ENTERED', max_length=100),
        ),
        migrations.AlterField(
            model_name='tc_status',
            name='CardType',
            field=models.CharField(default='BOS/NYNJ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tc_status_gui',
            name='CardType',
            field=models.CharField(blank=True, default='BLANK', max_length=100),
        ),
    ]
