# Generated by Django 3.2 on 2021-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0050_auto_20210408_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='gui_latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gui_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='releases',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
