# Generated by Django 3.2.1 on 2021-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0051_auto_20210414_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gui_latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AlterField(
            model_name='gui_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AlterField(
            model_name='latest_tc_status',
            name='CardType',
            field=models.CharField(default='NOT ENTERED', max_length=100),
        ),
        migrations.AlterField(
            model_name='latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AlterField(
            model_name='tc_status',
            name='CardType',
            field=models.CharField(default='BOS/NYNJ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, default='BLANK', max_length=50),
        ),
        migrations.AlterField(
            model_name='tc_status_gui',
            name='CardType',
            field=models.CharField(blank=True, default='BLANK', max_length=100),
        ),
    ]
