# Generated by Django 3.2.12 on 2022-03-01 08:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0051_auto_20220215_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='DockerVersion',
        ),
        migrations.AddField(
            model_name='releases',
            name='Runtime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
