# Generated by Django 3.1.6 on 2021-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0052_auto_20210407_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='releases',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
