# Generated by Django 3.2.1 on 2021-05-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0052_auto_20210506_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_status_gui',
            name='CardType',
        ),
    ]
