# Generated by Django 3.2.1 on 2021-05-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0053_remove_tc_status_gui_cardtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e2e',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='latest_tc_status',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='longevity',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='stress',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='tc_info',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='tc_info_gui',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='tc_status',
            name='CardType',
        ),
        migrations.RemoveField(
            model_name='ui',
            name='CardType',
        ),
    ]
