# Generated by Django 3.1.6 on 2021-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0053_releases_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
