# Generated by Django 3.1.6 on 2021-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0054_auto_20210409_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='gui_latest_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gui_tc_status',
            name='TestedOn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
