# Generated by Django 3.2.1 on 2021-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0054_auto_20210510_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2e',
            name='CardType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='latest_tc_status',
            name='CardType',
            field=models.CharField(default='NOT ENTERED', max_length=100),
        ),
        migrations.AddField(
            model_name='logs',
            name='CardType',
            field=models.CharField(blank=True, default='NO CARD PROVIDED', max_length=100),
        ),
        migrations.AddField(
            model_name='longevity',
            name='CardType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stress',
            name='CardType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tc_info',
            name='CardType',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='tc_info_gui',
            name='CardType',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='tc_status',
            name='CardType',
            field=models.CharField(default='BOS/NYNJ', max_length=100),
        ),
        migrations.AddField(
            model_name='tc_status_gui',
            name='CardType',
            field=models.CharField(blank=True, default='BLANK', max_length=100),
        ),
        migrations.AddField(
            model_name='ui',
            name='CardType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
