# Generated by Django 3.2.1 on 2021-05-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0055_auto_20210510_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_status_gui',
            name='CardType',
            field=models.CharField(blank=True, default='BLANK', max_length=10),
        ),
    ]
