# Generated by Django 3.2.1 on 2021-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0056_alter_tc_status_gui_cardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_status_gui',
            name='CardType',
            field=models.CharField(blank=True, default='BLANK', max_length=100),
        ),
    ]
