# Generated by Django 3.2.1 on 2021-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDB', '0057_alter_tc_status_gui_cardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_tc_status',
            name='CardType',
            field=models.CharField(default='NOT ENTERED', max_length=10),
        ),
    ]
